#!/bin/bash
#
# Generate changelogs from git tags.
#
# 
# Copyright 2016 Deutsches Zentrum für Luft- und Raumfahrt e.V. 
#         (German Aerospace Center), Earth Observation Center
# 
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -eu

function output_underline {
    _word="$1"
    # create a underline
    seq -s- $(echo "$_word" | wc -m) | tr -d '[:digit:]'
}

function output_git_log {
    START="$1"
    END="$2"
    git --no-pager log --no-merges \
        --format="format:  * %s [%h]" "${START}..${END}"  | fold -w 80 -s | sed -re 's.^([^ \t]).    \1.'
}

function output_changelog {
    TAGLIST=`git tag | grep -E '^[vV]?[0-9]+' | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort -r | awk '{print $4}'`
    REPO_ROOT=`git rev-parse --show-toplevel`

    LAST_IN_LIST=HEAD

    TITLE="Changelog for $(basename "$REPO_ROOT")"
    echo "$TITLE"
    output_underline "$TITLE"
    echo ""
    
    for TAG in $TAGLIST; do
        echo "$LAST_IN_LIST   ($(git log -1 --format=%ai "$LAST_IN_LIST"))"
        output_git_log "$TAG" "$LAST_IN_LIST"
        LAST_IN_LIST=$TAG
        echo ""
        echo ""
    done

    # changes since first commit
    FIRST_COMMIT=`git rev-list --max-parents=0 HEAD`
    echo "$LAST_IN_LIST"
    output_git_log "$FIRST_COMMIT" "$LAST_IN_LIST"
    echo ""
}

function output_help {
    cat <<EOT

Generate changelogs from git tags
---------------------------------

Uses tags matching a version number to generate a changelog. The changelog
will be written to stdout. The changelog is sorted by the creation date 
of the tags.

The following syntax for version numbers is unterstood:

    - <NUMBER>*
    - v<NUMBER>*
    - V<NUMBER>*

Usage:

    cd my-git-repository
    git-changelog

This script may also be used as a git subcommand when it is located on
the PATH:

    cd my-git-repository
    git changelog

EOT
}

while [[ $# -gt 0 ]]; do
    _key="$1"
    case $_key in
    -h|--help|help)
        output_help
        exit 0
    ;;
    esac
    shift # past argument or value
done

output_changelog

